### ISSUE TITLE
Not all references are optional in data

### ISSUE THREAD

**Issue by MJRamon** [Ninjdai1/letsdo-addon-structures#2]
Please make all entries `required: false`. For example, `letsdoaddon-structures\tags\worldgen\biome\has_structure\mangrove_hut.json`:
```
{
  "replace": false,
  "values": [
    "#bloomingnature:mangrove_swamp"
  ]
}
```
Has to be:
```
{
  "replace": false,
  "values": [
        {
            "id": "#bloomingnature:mangrove_swamp",
            "required": false
        }
  ]
}
```

And so on. There's a lot of error log spam that can be avoided and keep our client/server output clean.

**Comment by Ninjdai1** [comment]
That was actually intentional, to avoid structures generating if the required biome wasn't found, but I'll do that, thanks for the report :p
