### ISSUE TITLE
Unable to load certain tags

### ISSUE THREAD

**Issue by AmazingGabriel16** [Ninjdai1/letsdo-addon-structures#3]
MC version: 1.20.1
Fabric version: 0.15.11
Mod version: 1.7.1

Mod 'Load My Fucking Tags' has caught the issue of being unable to load certain tags such as 'letsdoaddon-structures:has_structure/mangrove_outpost'.

Here is the log:

<details>

- [10:43:27] [Worker-Main-10/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag letsdoaddon-structures:has_structure/mangrove_hut: #bloomingnature:mangrove_swamp (from fabric)
- [10:43:27] [Worker-Main-10/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag letsdoaddon-structures:has_structure/mangrove_pond: #bloomingnature:mangrove_swamp (from fabric)
- [10:43:27] [Worker-Main-10/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag letsdoaddon-structures:has_structure/swamp_well: #bloomingnature:mangrove_swamp (from fabric), #bloomingnature:swamp (from fabric)
- [10:43:27] [Worker-Main-10/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag letsdoaddon-structures:has_structure/mangrove_outpost: #bloomingnature:mangrove_swamp (from fabric)

</details>

**Comment by Ninjdai1** [comment]
Are you playing with bloomingnature ? If not, that's intended: as the mod is simply a datapack, the only way I have to detect if a mod is installed or not is using potentially non-existing tags to make the tag not load if the mod is not

**Comment by AmazingGabriel16** [comment]
No, looks like I don't have blooming nature installed.

Alright then, thanks for the heads up on it
